# Generated by Django 2.2.7 on 2019-11-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='updated_ap',
            new_name='updated_at',
        ),
    ]
