# Generated by Django 2.2.7 on 2019-12-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myStorage', '0002_albummodel_filemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albummodel',
            old_name='images',
            new_name='image',
        ),
    ]
